---
title: "ROC and PR curves"
author: "Francesco Pisu"
date: '2022-03-07'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages('pROC')
install.packages("PRROC")
install.packages("stringr")
install.packages("boot")
install.packages("MLmetrics")
install.packages("ggplot2")
install.packages("yardstick")
install.packages("ggsci")
install.packages("cvms")
install.packages("gridBase")
install.packages("dplyr")
install.packages("dcurves")
install.packages("gtsummary")
```

```{r}
library("pROC")
library("PRROC")
library("ROCR")
library("stringr")
library("boot")
library("MLmetrics")
library("ggplot2")
library("ggpubr")
library("yardstick")
library("ggsci")
library("cvms")
library("gridBase")
library("gridExtra")
library("grid")
library("dplyr")
library("tidyr")
library("reticulate")

library("dcurves")
library("gtsummary")
```


# Load predicted probabilities on both training and test sets
```{r}
#train = read.csv('../output/results/train_target_proba.csv')
test_gt_probas = read.csv('../output/predictions/test_preds_tuned_LGBM_all_features_0035_70trials.csv')
test_gt_probas_clinical = read.csv('../output/predictions/test_preds_tuned_LGBM_only_clinical_0035_70trials.csv')
test_gt_probas_calcification = read.csv('../output/predictions/test_preds_tuned_LGBM_only_calcification_0035_70trials.csv')
#external = read.csv("../input/external.csv")
```

```{r}
external$MLS_score = test_gt_probas$proba
external$symptoms = ifelse(external$symptoms == "yes", 1, 0)
external$prs_either = ifelse(external$prs_either == "yes", 1, 0)
```
```{r}
mod <- glm(symptoms ~ prs_either, external, family = binomial)
tbl <- tbl_regression(mod, exponentiate = TRUE)
```
```{r}
dca(symptoms ~ age + prs_either + MLS_score, 
    external, 
    as_probability = c("age", "prs_either"),
    thresholds = seq(0.0, 0.9, by = 0.01)) %>%
  net_intervention_avoided() %>%
  plot(smooth = TRUE)
```

```{r}
lightblue <- "#b0c4de"
salmon <- "#ff8c69"
```

```{r}
# Taking a look at different classification thresholds, all features
test.roc <- pROC::roc(test_gt_probas$target, test_gt_probas$proba, ci=TRUE, plot=TRUE,
    legacy.axes=TRUE, lwd=3, col=salmon)
test.coords <- pROC::coords(roc=test.roc, x = "all", transpose = FALSE)
test.coords[test.coords$sensitivity >= .50, ]

pROC::coords(test.roc, "best", best.method="youden", ret = c("threshold", "sensitivity", "specificity"), transpose = FALSE)
```
```{r}
# Taking a look at different classification thresholds, only clinical features
test.roc <- pROC::roc(test_gt_probas_clinical$target, test_gt_probas_clinical$proba, ci=TRUE, plot=TRUE,
    legacy.axes=TRUE, lwd=3, col=salmon)
test.coords <- pROC::coords(roc=test.roc, x = "all", transpose = FALSE)
test.coords[test.coords$sensitivity >= .50, ]

pROC::coords(test.roc, "best", best.method="youden", ret = c("threshold", "sensitivity", "specificity"), transpose = FALSE)
```

```{r}
# Taking a look at different classification thresholds, only calcification variables
test.roc <- pROC::roc(test_gt_probas_calcification$target, test_gt_probas_calcification$proba, ci=TRUE, plot=TRUE,
    legacy.axes=TRUE, lwd=3, col=salmon)
test.coords <- pROC::coords(roc=test.roc, x = "all", transpose = FALSE)
test.coords[test.coords$sensitivity >= .50, ]

pROC::coords(test.roc, "best", best.method="youden", ret = c("threshold", "sensitivity", "specificity"), transpose = FALSE)
```

# Compare ROC AUCs
```{r}
roc.calcification <- pROC::roc(test_gt_probas_calcification$target, test_gt_probas_calcification$proba)
roc.clinical <- pROC::roc(test_gt_probas_clinical$target, test_gt_probas_clinical$proba)
roc.all <- pROC::roc(test_gt_probas$target, test_gt_probas$proba)
```
```{r}
# Does plaque data provide better results when added to clinical data ?
pROC::roc.test(roc.calcification, roc.all)

# Does clinical data provide better results when added to calcification data ?
pROC::roc.test(roc.clinical, roc.all, method="bootstrap",
               boot.n=10000, boot.stratified=TRUE)
```



```{r}
use_condaenv("IPH", required = TRUE)
```

```{python}
def boot_prauc(preds_df_path):
  from sklearn.metrics import average_precision_score
  import pandas as pd
  import numpy as np
  import scikits.bootstrap as boot
  
  seed = 1303
  n_boots = 10000
  
  df = pd.read_csv(preds_df_path)
  
  conf_int, dist = boot.ci(data=(df["target"], df["proba"]),
                               statfunction=average_precision_score,
                               multi="paired",
                               n_samples=n_boots,
                               method="bca",
                               seed=seed,
                               return_dist=True)
  
  med = np.median(dist).item()
  
  #print(f"Metric name: {metric_name}, Median value:{med} ")
  test_prauc = "{:.2f} [{:.2f} - {:.2f}]".format(med, conf_int[0], conf_int[1])
  
  return test_prauc
```


# ROC curve
```{r}
plot_roc_ci <- function(df, target, proba) {
  # bootstrap AUCs for 95% CI
  set.seed(1303)
  
  fci<-function(data,indices,x,y){
     d<-as.data.frame(data[indices,])
     r<-MLmetrics::AUC(d[,2], d[,1])
     r
  }
  
  bootout <- boot(data=df,
                x=df[, target],
                y=df[, proba],
                R=2000,
                statistic=fci
                )
  
  roc.ci <- boot.ci(bootout, type="perc")
  roc.legend.text <- stringr::str_interp("Light GBM ($[.2f]{roc.ci$t0} [$[.2f]{roc.ci$percent[4]} - $[.2f]{roc.ci$percent[5]}])")
  
  # build ROC curve
  roc.obj <- pROC::roc(df[, target], df[, proba], plot=FALSE,
            legacy.axes=TRUE, percent=FALSE)
  
  # extract specificities and sensitivities from the roc object
  spec <- rev(roc.obj$specificities)
  sens <- rev(roc.obj$sensitivities)
  dat <- as.data.frame(cbind(1-spec, sens))
  colnames(dat) <- c("specificity", "sensitivity")
  
  # bootstrap confidence intervals around sensitivities 
  ciobj <- ci.se(roc.obj, specificities = seq(0, 1, l = nrow(dat)))
  dat.ci <- data.frame(x = as.numeric(rownames(ciobj)),
                       lower = ciobj[, 1],
                       upper = ciobj[, 3])
  
  points <- data.frame(x=c(1-0.814433,	1-0.40206186), 
                       y=c(0.5967742, 0.7741935),
                       shapes=c(4, 24),
                       lab=c("Youden's J", "Point 2"))
  points$shapes <- as.factor(points$shapes)
  points$lab <- as.factor(points$lab)
  
  ggplot(dat, aes(x = specificity, y = sensitivity, linetype=roc.legend.text)) +
  geom_segment(aes(x = 0, y = 0, xend = 1,yend = 1), alpha = 0.5, color="gray",
               linetype="dashed") +
  geom_path(aes(specificity, sensitivity), colour=salmon, size=1) +
  geom_ribbon(
      aes(x = 1-dat.ci$x, ymin = dat.ci$lower, ymax = dat.ci$upper),
      fill = lightblue,
      alpha = 0.2
  ) +
  geom_point(data=points, size=3, 
             fill="red", 
             mapping=aes(x=x, y=y, shape=shapes),
             ) +
  theme(aspect.ratio = 1) +
  labs(title="ROC curve", x="1 - Specificity", y="Sensitivity") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(colour="black", fill=NA, size=0.5),
        axis.title = element_text(size=16),
        axis.title.x = element_text(margin=margin(t=10)),
        axis.title.y = element_text(margin=margin(r=10)),
        plot.title = element_text(hjust=0.5, size=16, margin=margin(b=20)),
        legend.position = c(0.58, 0.12),
        legend.text = element_text(size=13)) +
  scale_linetype_manual(name='Legend',
                 #breaks=c('Linear', 'Quadratic', 'Cubic'),
                 #values=c('Cubic'='pink', 'Quadratic'='blue', 'Linear'='purple')
                 labels=c("lab"),
                 values=c("solid")
                 ) +
  #scale_fill_discrete(name="Legend") +
  scale_shape_manual(name="Legend", values=c(4, 24),
                     labels=points$lab)
}

roc.curve <- plot_roc_ci(external, "target", "proba")
roc.curve
```

```{r}
plot_roc_ci <- function(df, target, proba) {
  # bootstrap AUCs for 95% CI
  set.seed(1303)
  
  fci<-function(data,indices,x,y){
     d<-as.data.frame(data[indices,])
     r<-MLmetrics::AUC(d[,2], d[,1])
     r
  }
  
  bootout <- boot(data=df,
                x=df[, target],
                y=df[, proba],
                R=2000,
                statistic=fci
                )
  
  roc.ci <- boot.ci(bootout, type="perc")
  roc.legend.text <- stringr::str_interp("Light GBM ($[.2f]{roc.ci$t0} [$[.2f]{roc.ci$percent[4]} - $[.2f]{roc.ci$percent[5]}])")
  
  # build ROC curve
  roc.obj <- pROC::roc(df[, target], df[, proba], plot=FALSE,
            legacy.axes=TRUE, percent=FALSE)
  
  # extract specificities and sensitivities from the roc object
  spec <- rev(roc.obj$specificities)
  sens <- rev(roc.obj$sensitivities)
  dat <- as.data.frame(cbind(1-spec, sens))
  colnames(dat) <- c("specificity", "sensitivity")
  
  # bootstrap confidence intervals around sensitivities 
  ciobj <- ci.se(roc.obj, specificities = seq(0, 1, l = nrow(dat)))
  dat.ci <- data.frame(x = as.numeric(rownames(ciobj)),
                       lower = ciobj[, 1],
                       upper = ciobj[, 3])
  
  points <- data.frame(x=c(1-0.814433,	1-0.40206186), 
                       y=c(0.5967742, 0.7741935),
                       shapes=c(23, 24),
                       colors=c("#E54624", "#38C9B2"),
                       lab=c("Point 1 (Youden's Index)", "Point 2"))
  points$shapes <- as.factor(points$shapes)
  points$lab <- as.factor(points$lab)
  
  ggplot(dat, aes(x = specificity, y = sensitivity)) +
  geom_segment(aes(x = 0, y = 0, xend = 1,yend = 1), alpha = 0.5, color="gray",
               linetype="dashed") +
  geom_path(aes(specificity, sensitivity, 
                # color=roc.legend.text
                color=c(salmon)
                ), 
            # colour=salmon,
            linetype = "solid",
            size=1) +
  geom_ribbon(
      aes(x = 1-dat.ci$x, ymin = dat.ci$lower, ymax = dat.ci$upper),
      fill = lightblue,
      alpha = 0.2
  ) +
  geom_point(data=points, size=4,
             #fill="red",
             mapping=aes(x=x, y=y,
                         # color=shapes,
                         color=colors,
                         shape=shapes,
                         # fill=colors
                         ),
             ) +
  theme(aspect.ratio = 1) +
  labs(title="ROC curve", x="1 - Specificity", y="Sensitivity") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(colour="black", fill=NA, size=0.5),
        axis.title = element_text(size=16),
        axis.title.x = element_text(margin=margin(t=10)),
        axis.title.y = element_text(margin=margin(r=10)),
        plot.title = element_text(hjust=0.5, size=16, margin=margin(b=20)),
        legend.position = c(0.58, 0.12),
        legend.text = element_text(size=13),
        legend.title=element_blank()) +
  scale_color_manual("Pippo", 
                     values=c(salmon, "#E54624", "#38C9B2"),
                     labels=c(roc.legend.text, 
                              "Point 1 (Youden's Index)", 
                              "Point 2"))
  #scale_linetype_manual("",
                 #breaks=c('Linear', 'Quadratic', 'Cubic'),
                 #values=c('Cubic'='pink', 'Quadratic'='blue', 'Linear'='purple')
                 #labels=c(roc.legend.text),
  #               labels=c(roc.legend.text),
  #               values=c("solid")
  #               ) +
  #scale_fill_discrete(name="Legend") +
  # scale_shape_manual("Pippo", values=c(23, 24),
  #                    labels=c("Point 1 (Youden's Index)", 
  #                             "Point 2")
  #                    # labels=points$lab
  #                    )

  # scale_color_identity(
  #   name="Pippo",
  #   breaks=c(salmon, "#E54624", "#38C9B2"),
  #   labels=c(roc.legend.text, "Point 1 (Youden's Index)", "Point 2"),
  #   guide="legend"
  # ) 
  # scale_shape_manual(
  #   name="Pippo",
  #   values=c(23, 24),
  #   # # labels=c(roc.legend.text, "Point 1 (Youden's Index)", "Point 2"),
  #   # guide="legend"
  #   
  # )
}

roc.curve <- plot_roc_ci(external, "target", "proba")
roc.curve
```

```{r}
plot_roc_ci <- function(df, target, proba) {
  # bootstrap AUCs for 95% CI
  set.seed(1303)
  
  fci<-function(data,indices,x,y){
     d<-as.data.frame(data[indices,])
     r<-MLmetrics::AUC(d[,2], d[,1])
     r
  }
  
  bootout <- boot(data=df,
                x=df[, target],
                y=df[, proba],
                R=10000,
                statistic=fci
                )
  
  roc.ci <- boot.ci(bootout, type="perc")
  roc.legend.text <- stringr::str_interp("Light GBM ($[.2f]{roc.ci$t0} [$[.2f]{roc.ci$percent[4]} - $[.2f]{roc.ci$percent[5]}])")
  
  # build ROC curve
  roc.obj <- pROC::roc(df[, target], df[, proba], plot=FALSE,
            legacy.axes=TRUE, percent=FALSE)
  
  # extract specificities and sensitivities from the roc object
  spec <- rev(roc.obj$specificities)
  sens <- rev(roc.obj$sensitivities)
  dat <- as.data.frame(cbind(1-spec, sens))
  colnames(dat) <- c("specificity", "sensitivity")
  
  # bootstrap confidence intervals around sensitivities 
  ciobj <- ci.se(roc.obj, specificities = seq(0, 1, l = nrow(dat)))
  dat.ci <- data.frame(x = as.numeric(rownames(ciobj)),
                       lower = ciobj[, 1],
                       upper = ciobj[, 3])
  
  points <- data.frame(x=c(1-0.814433,	1-0.40206186), 
                       y=c(0.5967742, 0.7741935),
                       colors=c("#2E86C1", "#E54624"),
                       shapes=c(23, 24),
                       lab=c("Point 1 (Youden's J)", "Point 2"))
  points$shapes <- as.factor(points$shapes)
  points$lab <- as.factor(points$lab)
  
  ggplot(dat, aes(x = specificity, y = sensitivity, linetype=roc.legend.text)) +
  geom_segment(aes(x = 0, y = 0, xend = 1,yend = 1), alpha = 0.5, color="gray",
               linetype="dashed") +
  geom_path(aes(specificity, sensitivity, linetype=roc.legend.text), colour=salmon, size=1) +
  geom_ribbon(
      aes(x = 1-dat.ci$x, ymin = dat.ci$lower, ymax = dat.ci$upper),
      fill = lightblue,
      alpha = 0.2
  ) +
  geom_point(data=points, size=3, 
             #fill="red", 
             mapping=aes(x=x, y=y, shape=shapes, fill=colors),
             ) +
  theme(aspect.ratio = 1) +
  labs(title="", x="1 - Specificity", y="Sensitivity") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(colour="black", fill=NA, size=0.5),
        axis.title = element_text(size=16),
        axis.title.x = element_text(margin=margin(t=10)),
        axis.title.y = element_text(margin=margin(r=10)),
        plot.title = element_text(hjust=0.5, size=16, margin=margin(b=20)),
        legend.position = c(0.68, 0.21),
        legend.text = element_text(size=13)) +
  scale_linetype_manual(name='Model AUC',
                 #breaks=c('Linear', 'Quadratic', 'Cubic'),
                 #values=c('Cubic'='pink', 'Quadratic'='blue', 'Linear'='purple')
                 #labels=c(roc.legend.text),
                 values=c("solid")
                 ) +
  #scale_fill_discrete(name="Legend") +
  scale_shape_manual(name="Thresholds", values=c(23, 24),
                     labels=points$lab) +
  scale_fill_manual(name="Thresholds", values=c("#E54624", "#2E86C1"),
                     labels=points$lab)
}

roc.curve <- plot_roc_ci(external, "target", "proba")
roc.curve
```

```{r}
# only one operational point
plot_roc_ci <- function(df, target, proba, sens_y, spec_x) {
  # bootstrap AUCs for 95% CI
  set.seed(1303)
  
  fci<-function(data,indices,x,y){
     d<-as.data.frame(data[indices,])
     r<-MLmetrics::AUC(d[,2], d[,1])
     r
  }
  
  bootout <- boot(data=df,
                x=df[, target],
                y=df[, proba],
                R=10000,
                statistic=fci
                )
  
  roc.ci <- boot.ci(bootout, type="perc")
  roc.legend.text <- stringr::str_interp("Light GBM ($[.2f]{roc.ci$t0} [$[.2f]{roc.ci$percent[4]} - $[.2f]{roc.ci$percent[5]}])")
  
  # build ROC curve
  roc.obj <- pROC::roc(df[, target], df[, proba], plot=FALSE,
            legacy.axes=TRUE, percent=FALSE)
  
  # extract specificities and sensitivities from the roc object
  spec <- rev(roc.obj$specificities)
  sens <- rev(roc.obj$sensitivities)
  dat <- as.data.frame(cbind(1-spec, sens))
  colnames(dat) <- c("specificity", "sensitivity")
  
  # bootstrap confidence intervals around sensitivities 
  ciobj <- ci.se(roc.obj, specificities = seq(0, 1, l = nrow(dat)))
  dat.ci <- data.frame(x = as.numeric(rownames(ciobj)),
                       lower = ciobj[, 1],
                       upper = ciobj[, 3])
  
  # points <- data.frame(x=c(1-0.742268), 
  #                      y=c(0.6451613),
  #                      colors=c("#2E86C1"),
  #                      shapes=c(23),
  #                      lab=c("Youden's J"))
  points <- data.frame(x=c(1-spec_x), 
                       y=c(sens_y),
                       colors=c("#2E86C1"),
                       shapes=c(23),
                       lab=c("Youden's J"))  
  points$shapes <- as.factor(points$shapes)
  points$lab <- as.factor(points$lab)
  
  ggplot(dat, aes(x = specificity, y = sensitivity, linetype=roc.legend.text)) +
  geom_segment(aes(x = 0, y = 0, xend = 1,yend = 1), alpha = 0.5, color="gray",
               linetype="dashed") +
  geom_path(aes(specificity, sensitivity, linetype=roc.legend.text), colour=salmon, size=1) +
  geom_ribbon(
      aes(x = 1-dat.ci$x, ymin = dat.ci$lower, ymax = dat.ci$upper),
      fill = lightblue,
      alpha = 0.2
  ) +
  geom_point(data=points, size=3, 
             #fill="red", 
             mapping=aes(x=x, y=y, shape=shapes, fill=colors),
             ) +
  theme(aspect.ratio = 1) +
  labs(title="", x="1 - Specificity", y="Sensitivity") +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(colour="black", fill=NA, size=0.5),
        axis.title = element_text(size=16),
        axis.title.x = element_text(margin=margin(t=10), size=20),
        axis.title.y = element_text(margin=margin(r=10), size=20),
        plot.title = element_text(hjust=0.5, size=16, margin=margin(b=20)),
        legend.position = c(0.68, 0.11),
        legend.text = element_text(size=20)) +
  scale_linetype_manual(name='Model AUC',
                 #breaks=c('Linear', 'Quadratic', 'Cubic'),
                 #values=c('Cubic'='pink', 'Quadratic'='blue', 'Linear'='purple')
                 #labels=c(roc.legend.text),
                 values=c("solid")
                 ) +
  #scale_fill_discrete(name="Legend") +
  scale_shape_manual(name="Operational point", values=c(23, 24),
                     labels=points$lab) +
  scale_fill_manual(name="Operational point", values=c("#E54624", "#2E86C1"),
                     labels=points$lab)
}

roc.curve.all <- plot_roc_ci(test_gt_probas, "target", "proba", sens=0.6451613, spec=0.742268)
roc.curve.all
```
```{r}
roc.curve.calcification <- plot_roc_ci(test_gt_probas_calcification, "target", "proba", 
                         sens_y=0.6451613, 
                         spec_x=0.7938144)
roc.curve.calcification
```

```{r}
roc.curve.clinical <- plot_roc_ci(test_gt_probas_clinical, "target", "proba", sens=0.5806452, spec=0.6804124)
roc.curve.clinical
```

# Precision-recall curve
```{r}
plot_pr_ci <- function(df, target, proba, preds_path) {
  # bootstrap AUCs for 95% CI
  prauc.ci <- py$boot_prauc(preds_path)
  # $[.2f]{prauc.ci$t0} [$[.2f]{prauc.ci$percent[4]} - $[.2f]{prauc.ci$percent[5]}]
  pr.legend.text <- stringr::str_interp("Light GBM (${prauc.ci})")
  
  # build PR curve
  roc.obj <- pROC::roc(df[, target], df[, proba], plot=FALSE, legacy.axes=TRUE, percent=FALSE)
  prcoords <- coords(roc.obj, "all", ret = c("threshold", "recall", "precision"), transpose = FALSE)
  prcoords[nrow(prcoords), 3] <- 1.0000
  
  
  # bootstrap recall/precision coordinates for 95% confidence bands
  pr.cis <- ci.coords(roc.obj, prcoords$threshold, ret=c("recall", "precision"))
  pr.cis <- data.frame(pr.cis[2]) # convert precision coords to data frame
  pr.cis.df <- data.frame(x = prcoords$recall,
                       lower = pr.cis[, 1],
                       upper = pr.cis[, 3])
  
  # compute baseline (proportion of positive samples)
  npos.test = length(which(df[, target] == 1))
  nneg.test = length(which(df[, target] == 0))
  prop.pos = npos.test / (npos.test + nneg.test)
  
  ggplot(prcoords, aes(recall, precision, linetype=pr.legend.text)) + 
    geom_path(aes(recall, precision), colour=salmon, size=1) +
    geom_ribbon(aes(x=pr.cis.df$x, ymin=pr.cis.df$lower, ymax=pr.cis.df$upper), 
                alpha=0.3,
                fill=lightblue) +
    geom_hline(yintercept=prop.pos, linetype='dashed', color='gray') +
    theme(aspect.ratio = 1) +
    coord_cartesian(ylim = c(0.0, 1.0)) +
    labs(title="", x="Recall", y="Precision") +
    theme(
          panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          panel.background = element_blank(), 
          panel.border = element_rect(colour="black", fill=NA, size=0.5),
          axis.title = element_text(size=16),
          axis.title.x = element_text(margin=margin(t=10), size=20),
          axis.title.y = element_text(margin=margin(r=10), size=20),
          plot.title = element_text(hjust=0.5, size=16, margin=margin(b=20)),
          legend.position = c(0.58, 0.12),
          legend.text = element_text(size=20)
          ) +
    scale_linetype_manual(name='', values=c("solid"))
}
```

## All features
```{r}
pr.curve.all <- plot_pr_ci(test_gt_probas, "target", "proba",
                       preds_path = '../output/predictions/test_preds_tuned_LGBM_all_features_0035_70trials.csv')
pr.curve.all
```

## Only calcification
```{r}
pr.curve.calcification <- plot_pr_ci(test_gt_probas_calcification, "target", "proba",
                       preds_path = '../output/predictions/test_preds_tuned_LGBM_only_calcification_0035_70trials.csv')
pr.curve.calcification
```
## Only clinical
```{r}
pr.curve.clinical <- plot_pr_ci(test_gt_probas_clinical, "target", "proba",
                       preds_path = '../output/predictions/test_preds_tuned_LGBM_only_clinical_0035_70trials.csv')
pr.curve.clinical
```

# Confusion matrix
```{r}
make_cm <- function(df, target, proba, threshold) {
  # Build confusion matrix using the cvms package
  df.copy <- data.frame(df)
  
  # Dichotomize predicted probabilities
  df.copy$labels <- ifelse(df.copy[, proba] >= threshold, 1, 0)
  df.copy$target <- ifelse(df.copy[, target] == "1", "Symptomatic", "Asymptomatic")
  df.copy$labels <- ifelse(df.copy[, "labels"] == "1", "Symptomatic", "Asymptomatic")
  
  eval <- cvms::evaluate(df.copy, target_col = "target", prediction_cols = "labels",
                       type="binomial")
  
  cm.plot <- cvms::plot_confusion_matrix(eval, 
                                         target_col = "Target",
                                         prediction_col = "Prediction",
                                         add_row_percentages = FALSE,
                                         add_col_percentages = FALSE,
                                         palette="Blues",
                                         font_counts = cvms::font(size=23, 
                                                                  color="#342d2d", 
                                                                  vjust=23),
                                         font_normalized = cvms::font(size=23, 
                                                                      color="#342d2d", 
                                                                      vjust=-0.5)) +
    ggplot2::ggtitle("") +
    ggplot2::theme(axis.title = ggplot2::element_text(size=23),
                   axis.title.y = ggplot2::element_text(margin = ggplot2::margin(r=25)),
                   axis.text.x = ggplot2::element_text(size=23),
                   axis.text.y = ggplot2::element_text(size=23),
                   axis.ticks.length = ggplot2::unit(-1, "cm"),
                   plot.title = ggplot2::element_text(size=23, 
                                                      hjust=0.5, 
                                                      vjust=4.0,
                                                      family = "sans")
    ) +
    ggplot2::labs(x = "Actual", y = "Predicted")
}
```

## All features, youden
```{r}
cm.plot.all <- make_cm(test_gt_probas, "target", "proba", 0.4853442)
```

## Only calcification, youden
```{r}
cm.plot.calcification <- make_cm(test_gt_probas_calcification, "target", "proba", 0.5282613)
```

## Only clinical
```{r}
cm.plot.clinical <- make_cm(test_gt_probas_clinical, "target", "proba", 0.5055034)
```

## Old 2x2 grid
```{r}
g2 <- ggarrange(plotlist=lapply(list(roc.curve, pr.curve, cm.plot.youden, cm.plot.point2), "+", theme(plot.margin=margin(0, 80, 0, 0))),
          nrow=2,
          ncol=2,
          labels=c("A", "B", "C", "D"),
          font.label = list(size=25))
g2 <- annotate_figure(g2, top = textGrob("", gp=gpar(fontsize=20, font=1)))
#ggsave(file="../output/plots/roc_and_pr_curves.pdf", g2, width = 14, height = 12)
#ggsave(file="../output/plots/TIFF/roc_and_pr_curves.tiff", g2, width = 14, height = 12, device="tiff", dpi=700)
g2
```

## All features
```{r}
tiff("../output/plots/TIFF/roc_and_pr_curves_test.tiff", units="in", width=25, height=8, res=1200, compression = "lzw",
     type="cairo")
g2 <- ggarrange(plotlist=lapply(list(roc.curve.all, pr.curve.all, cm.plot.all), "+", theme(plot.margin=margin(0, 20, 0, 0))),
          nrow=1,
          ncol=3,
          labels=c("A", "B", "C"),
          font.label = list(size=25))
g2 <- annotate_figure(g2, top = textGrob("", gp=gpar(fontsize=20, font=1)))
g2
dev.off()
```

## Only calcification
```{r}
tiff("../output/plots/TIFF/roc_and_pr_curves_test_only_calcification.tiff", units="in", width=25, height=10, res=1200, compression = "lzw",
     type="cairo")
g2 <- ggarrange(plotlist=lapply(list(roc.curve.calcification, pr.curve.calcification, cm.plot.calcification), "+", theme(plot.margin=margin(0, 200, 0, 0))),
          nrow=1,
          ncol=3,
          labels=c("A", "B", "C"),
          font.label = list(size=25))
g2 <- annotate_figure(g2, top = textGrob("", gp=gpar(fontsize=20, font=1)))
g2
dev.off()
```

## Only clinical data
```{r}
tiff("../output/plots/TIFF/roc_and_pr_curves_test_only_clinical.tiff", units="in", width=25, height=6, res=1200, compression = "lzw",
     type="cairo")
g2 <- ggarrange(plotlist=lapply(list(roc.curve.clinical, pr.curve.clinical, cm.plot.clinical), "+", theme(plot.margin=margin(0, 200, 0, 0))),
          nrow=1,
          ncol=3,
          labels=c("A", "B", "C"),
          font.label = list(size=25))
g2 <- annotate_figure(g2, top = textGrob("", gp=gpar(fontsize=20, font=1)))
g2
dev.off()
```

## All sets
```{r}
tiff("../output/plots/TIFF/roc_and_pr_curves_test_all_sets.tiff", units="in", width=27, height=20, res=1200, compression = "lzw",
     type="cairo")
g2 <- ggarrange(plotlist=lapply(list(roc.curve.all, pr.curve.all, cm.plot.all,
                                     roc.curve.clinical, pr.curve.clinical, cm.plot.clinical,
                                     roc.curve.calcification, pr.curve.calcification, cm.plot.calcification), "+", theme(plot.margin=margin(0, 200, 0, 0))),
          nrow=3,
          ncol=3,
          labels=c("A", "B", "C", "D", "E", "F", "G", "H", "I"),
          font.label = list(size=25))
g2 <- annotate_figure(g2, top = textGrob("", gp=gpar(fontsize=20, font=1)))
g2
dev.off()
```

# calibration
```{r}
install.packages("ResourceSelection")
install.packages("givitiR")
library("ResourceSelection")
library("givitiR")
```

```{r}
cb <- givitiCalibrationBelt(o = test_gt_probas$target, e = test_gt_probas$proba,
                            devel = "external", confLevels= .95)
plot(cb, main = "",
                          xlab = "LightGBM predicted probability",
                          ylab = "Observed: proportion of events", col="blue")
```

```{r}
tiff("../output/plots/TIFF/calibration.tiff", units="in", width=8, height=5,res=1200, compression = "lzw",
     type="cairo")
#options("devEval/args/path"=file.path("../output/plots/TIFF/"))

d <- data.frame(cb$seqP, cb$cbBoundByConfLevel)
calib <- ggplot(data=d, aes(x=cb.seqP)) +
  geom_ribbon(aes(ymin=L, ymax=U), color="#426A9E", fill="white", size=2) +
  #geom_ribbon(aes(ymin=L.1, ymax=U.1), fill="#b0c4de") +
  #geom_abline(slope=1, intercept=0, color="#D34B22", size=1.5, linetype="solid") +
  geom_segment(aes(x=0.22, y=0.22, xend=0.86, yend=0.86), color="#D34B22", size=1.5) +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(colour="black", fill=NA, size=0.5),
        axis.title = element_text(size=16),
        axis.title.x = element_text(margin=margin(t=10)),
        axis.title.y = element_text(margin=margin(r=10)),
        plot.title = element_text(hjust=0.5, size=16, margin=margin(b=20)),
        legend.position = c(0.58, 0.12),
        legend.text = element_text(size=13),
        legend.title=element_blank()) +
  labs(title="", y="Observed: proportion of events", x="Predicted probabilities")
#devEval("tiff", name="calibration", width=120, height=800, calib)
#ggsave(file="../output/plots/TIFF/calibration.tiff", calib, width = 8, height = 5, device="tiff", dpi=800, compression = "lzw", type="cairo")
calib
dev.off()
```


